# fly.toml app configuration file generated for discord-webhook-lively-glade-1537 on 2025-07-13T22:23:01+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'discord-webhook-lively-glade-1537'
primary_region = 'nrt'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[processes]
cron = ""

[[cron]]
  schedule = "*/5 * * * *"
  command = "node scripts/access_rakuten.js"

[env]
    MONITOR_URL = "https://books.rakuten.co.jp/rb/18210510/?l-id=search-all-non-nohit-20090624"
    URL_LABEL = "switch2単体"
    DISCORD_WEBHOOK = "https://discord.com/api/webhooks/1393877281960890528/ufoPpN4_y_8E57IuCWFw5C3HLqPLV4gGOghvhDviFNyfkBEphmCtjU6XDBAWj7Ma3Tc0"