name: Rakuten Monitor

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        url_name:
          - "https://books.rakuten.co.jp/rb/18210486/?l-id=search-c-item-01"
          - "https://books.rakuten.co.jp/rb/18210481/?bkts=1"
          - "https://books.rakuten.co.jp/rb/18210481/?bkts=1"
          - "https://books.rakuten.co.jp/rb/18297054/?bkts=1&l-id=search-c-item-text-02"
          - "https://books.rakuten.co.jp/rb/18297055/?bkts=1&l-id=search-c-item-text-01"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
      
      - name: Install Chrome
        run: npx puppeteer browsers install chrome

      - name: Run monitoring script
        env:
          MONITOR_URL: ${{ matrix.url_name }}
          DISCORD_WEBHOOK: "https://discord.com/api/webhooks/1393877281960890528/ufoPpN4_y_8E57IuCWFw5C3HLqPLV4gGOghvhDviFNyfkBEphmCtjU6XDBAWj7Ma3Tc0"
        run: node scripts/access_rakuten.js